/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Campaign {
  'id' : string,
  'status' : CampaignStatus,
  'name' : string,
  'createdAt' : Time,
  'updatedAt' : Time,
  'offerIds' : Array<OfferWeight>,
  'trackingDomain' : string,
  'trafficSourceId' : string,
}
export interface CampaignStats {
  'epc' : bigint,
  'roi' : bigint,
  'clicks' : bigint,
  'revenue' : bigint,
  'uniqueClicks' : bigint,
  'cost' : bigint,
  'campaignId' : string,
  'conversionRate' : bigint,
  'conversions' : bigint,
}
export type CampaignStatus = { 'active' : null } |
  { 'archived' : null } |
  { 'paused' : null };
export interface ClickEvent {
  'id' : string,
  'os' : string,
  'landingPageUrl' : string,
  'country' : string,
  'city' : string,
  'campaignId' : string,
  'referrerUrl' : string,
  'uniqueClickId' : string,
  'timestamp' : Time,
  'deviceType' : string,
  'browser' : string,
  'ipAddress' : string,
}
export interface Condition {
  'field' : string,
  'value' : string,
  'operator' : string,
}
export interface ConversionEvent {
  'id' : string,
  'status' : ConversionStatus,
  'revenue' : bigint,
  'campaignId' : string,
  'timestamp' : Time,
  'offerId' : string,
  'payout' : number,
  'clickId' : string,
}
export type ConversionStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'declined' : null };
export type CostModel = { 'cpa' : null } |
  { 'cpc' : null } |
  { 'cpm' : null };
export interface Domain {
  'id' : string,
  'status' : DomainStatus,
  'domainType' : DomainType,
  'name' : string,
  'createdAt' : Time,
  'updatedAt' : Time,
}
export type DomainStatus = { 'active' : null } |
  { 'inactive' : null };
export type DomainType = { 'postback' : null } |
  { 'admin' : null } |
  { 'campaign' : null };
export interface Flow {
  'id' : string,
  'name' : string,
  'createdAt' : Time,
  'campaignId' : string,
  'updatedAt' : Time,
  'rules' : Array<RoutingRule>,
}
export interface Offer {
  'id' : string,
  'url' : string,
  'status' : OfferStatus,
  'name' : string,
  'createdAt' : Time,
  'updatedAt' : Time,
  'currency' : string,
  'payout' : bigint,
}
export type OfferStatus = { 'active' : null } |
  { 'paused' : null };
export interface OfferWeight { 'weight' : bigint, 'offerId' : string }
export interface Parameter {
  'name' : string,
  'type' : ParameterType,
  'description' : string,
  'required' : boolean,
}
export type ParameterType = { 'float' : null } |
  { 'integer' : null } |
  { 'text' : null } |
  { 'boolean' : null } |
  { 'currency' : null } |
  { 'percentage' : null };
export interface RoutingRule {
  'targetOffers' : Array<OfferWeight>,
  'conditions' : Array<Condition>,
}
export type Time = bigint;
export interface TrafficSource {
  'id' : string,
  'costModel' : CostModel,
  'name' : string,
  'createdAt' : Time,
  'parameters' : Array<Parameter>,
  'postbackUrl' : string,
  'updatedAt' : Time,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCampaign' : ActorMethod<
    [string, string, Array<OfferWeight>, CampaignStatus, string],
    Campaign
  >,
  'createDomain' : ActorMethod<[string, DomainType, DomainStatus], Domain>,
  'createFlow' : ActorMethod<[string, string, Array<RoutingRule>], Flow>,
  'createOffer' : ActorMethod<
    [string, string, bigint, string, OfferStatus],
    Offer
  >,
  'createTrafficSource' : ActorMethod<
    [string, string, CostModel, Array<Parameter>],
    TrafficSource
  >,
  'deleteCampaign' : ActorMethod<[string], undefined>,
  'deleteDomain' : ActorMethod<[string], undefined>,
  'deleteFlow' : ActorMethod<[string], undefined>,
  'deleteOffer' : ActorMethod<[string], undefined>,
  'deleteTrafficSource' : ActorMethod<[string], undefined>,
  'getAllCampaigns' : ActorMethod<[], Array<Campaign>>,
  'getAllDomains' : ActorMethod<[], Array<Domain>>,
  'getAllDomainsByType' : ActorMethod<[DomainType], Array<Domain>>,
  'getAllFlows' : ActorMethod<[], Array<Flow>>,
  'getAllOffers' : ActorMethod<[], Array<Offer>>,
  'getAllTrafficSources' : ActorMethod<[], Array<TrafficSource>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCampaign' : ActorMethod<[string], Campaign>,
  'getCampaignStats' : ActorMethod<[], Array<CampaignStats>>,
  'getClicksLog' : ActorMethod<[bigint, bigint], Array<ClickEvent>>,
  'getConversionsLog' : ActorMethod<[bigint, bigint], Array<ConversionEvent>>,
  'getDomain' : ActorMethod<[string], Domain>,
  'getFlow' : ActorMethod<[string], Flow>,
  'getOffer' : ActorMethod<[string], Offer>,
  'getTrafficSource' : ActorMethod<[string], TrafficSource>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initialize' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'recordClick' : ActorMethod<
    [string, string, string, string, string, string, string, string, string],
    ClickEvent
  >,
  'recordConversion' : ActorMethod<
    [string, string, string, number, bigint, ConversionStatus],
    ConversionEvent
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateCampaign' : ActorMethod<
    [string, string, string, Array<OfferWeight>, CampaignStatus, string],
    Campaign
  >,
  'updateDomain' : ActorMethod<
    [string, string, DomainType, DomainStatus],
    Domain
  >,
  'updateFlow' : ActorMethod<
    [string, string, string, Array<RoutingRule>],
    Flow
  >,
  'updateOffer' : ActorMethod<
    [string, string, string, bigint, string, OfferStatus],
    Offer
  >,
  'updateTrafficSource' : ActorMethod<
    [string, string, string, CostModel, Array<Parameter>],
    TrafficSource
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];