/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CampaignStatus = IDL.Variant({
  'active' : IDL.Null,
  'archived' : IDL.Null,
  'paused' : IDL.Null,
});
export const Time = IDL.Int;
export const Campaign = IDL.Record({
  'id' : IDL.Text,
  'status' : CampaignStatus,
  'name' : IDL.Text,
  'createdAt' : Time,
  'updatedAt' : Time,
  'trackingDomain' : IDL.Text,
  'campaignKey' : IDL.Text,
  'trafficSourceId' : IDL.Text,
});
export const DomainType = IDL.Variant({
  'postback' : IDL.Null,
  'admin' : IDL.Null,
  'campaign' : IDL.Null,
});
export const DomainStatus = IDL.Variant({
  'active' : IDL.Null,
  'inactive' : IDL.Null,
});
export const Domain = IDL.Record({
  'id' : IDL.Text,
  'status' : DomainStatus,
  'domainType' : DomainType,
  'name' : IDL.Text,
  'createdAt' : Time,
  'updatedAt' : Time,
});
export const OfferWeight = IDL.Record({
  'weight' : IDL.Nat,
  'offerId' : IDL.Text,
});
export const Condition = IDL.Record({
  'field' : IDL.Text,
  'value' : IDL.Text,
  'operator' : IDL.Text,
});
export const RoutingRule = IDL.Record({
  'targetOffers' : IDL.Vec(OfferWeight),
  'conditions' : IDL.Vec(Condition),
});
export const Flow = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Time,
  'campaignId' : IDL.Text,
  'updatedAt' : Time,
  'rules' : IDL.Vec(RoutingRule),
});
export const OfferStatus = IDL.Variant({
  'active' : IDL.Null,
  'paused' : IDL.Null,
});
export const Offer = IDL.Record({
  'id' : IDL.Text,
  'url' : IDL.Text,
  'status' : OfferStatus,
  'name' : IDL.Text,
  'createdAt' : Time,
  'updatedAt' : Time,
  'currency' : IDL.Text,
  'payout' : IDL.Nat,
});
export const StreamState = IDL.Variant({
  'active' : IDL.Null,
  'paused' : IDL.Null,
});
export const Stream = IDL.Record({
  'id' : IDL.Text,
  'weight' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : Time,
  'campaignId' : IDL.Text,
  'updatedAt' : Time,
  'state' : StreamState,
  'position' : IDL.Nat,
  'offerId' : IDL.Text,
});
export const CostModel = IDL.Variant({
  'cpa' : IDL.Null,
  'cpc' : IDL.Null,
  'cpm' : IDL.Null,
});
export const ParameterType = IDL.Variant({
  'float' : IDL.Null,
  'integer' : IDL.Null,
  'text' : IDL.Null,
  'boolean' : IDL.Null,
  'currency' : IDL.Null,
  'percentage' : IDL.Null,
});
export const Parameter = IDL.Record({
  'name' : IDL.Text,
  'type' : ParameterType,
  'description' : IDL.Text,
  'required' : IDL.Bool,
});
export const TrafficSource = IDL.Record({
  'id' : IDL.Text,
  'costModel' : CostModel,
  'name' : IDL.Text,
  'createdAt' : Time,
  'parameters' : IDL.Vec(Parameter),
  'postbackUrl' : IDL.Text,
  'updatedAt' : Time,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const CampaignStats = IDL.Record({
  'epc' : IDL.Nat,
  'roi' : IDL.Nat,
  'clicks' : IDL.Nat,
  'revenue' : IDL.Nat,
  'uniqueClicks' : IDL.Nat,
  'cost' : IDL.Nat,
  'campaignId' : IDL.Text,
  'conversionRate' : IDL.Nat,
  'conversions' : IDL.Nat,
});
export const ClickEvent = IDL.Record({
  'id' : IDL.Text,
  'os' : IDL.Text,
  'landingPageUrl' : IDL.Text,
  'country' : IDL.Text,
  'city' : IDL.Text,
  'campaignId' : IDL.Text,
  'referrerUrl' : IDL.Text,
  'uniqueClickId' : IDL.Text,
  'timestamp' : Time,
  'deviceType' : IDL.Text,
  'browser' : IDL.Text,
  'ipAddress' : IDL.Text,
});
export const ConversionStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'declined' : IDL.Null,
});
export const ConversionEvent = IDL.Record({
  'id' : IDL.Text,
  'status' : ConversionStatus,
  'revenue' : IDL.Nat,
  'campaignId' : IDL.Text,
  'timestamp' : Time,
  'offerId' : IDL.Text,
  'payout' : IDL.Float64,
  'clickId' : IDL.Text,
});
export const ErrorLog = IDL.Record({
  'id' : IDL.Text,
  'context' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const ProcessClickResult = IDL.Record({
  'campaignId' : IDL.Text,
  'offerUrl' : IDL.Text,
  'clickId' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCampaign' : IDL.Func(
      [IDL.Text, IDL.Text, CampaignStatus, IDL.Text],
      [Campaign],
      [],
    ),
  'createDomain' : IDL.Func([IDL.Text, DomainType, DomainStatus], [Domain], []),
  'createFlow' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(RoutingRule)],
      [Flow],
      [],
    ),
  'createOffer' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, OfferStatus],
      [Offer],
      [],
    ),
  'createStream' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, StreamState, IDL.Nat],
      [Stream],
      [],
    ),
  'createTrafficSource' : IDL.Func(
      [IDL.Text, IDL.Text, CostModel, IDL.Vec(Parameter)],
      [TrafficSource],
      [],
    ),
  'deleteCampaign' : IDL.Func([IDL.Text], [], []),
  'deleteDomain' : IDL.Func([IDL.Text], [], []),
  'deleteFlow' : IDL.Func([IDL.Text], [], []),
  'deleteOffer' : IDL.Func([IDL.Text], [], []),
  'deleteStream' : IDL.Func([IDL.Text], [], []),
  'deleteTrafficSource' : IDL.Func([IDL.Text], [], []),
  'generateInviteToken' : IDL.Func([IDL.Text], [IDL.Text], []),
  'getAllCampaigns' : IDL.Func([], [IDL.Vec(Campaign)], ['query']),
  'getAllDomains' : IDL.Func([], [IDL.Vec(Domain)], ['query']),
  'getAllDomainsByType' : IDL.Func([DomainType], [IDL.Vec(Domain)], ['query']),
  'getAllFlows' : IDL.Func([], [IDL.Vec(Flow)], ['query']),
  'getAllOffers' : IDL.Func([], [IDL.Vec(Offer)], ['query']),
  'getAllStreams' : IDL.Func([], [IDL.Vec(Stream)], ['query']),
  'getAllTrafficSources' : IDL.Func([], [IDL.Vec(TrafficSource)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCampaign' : IDL.Func([IDL.Text], [Campaign], ['query']),
  'getCampaignByKey' : IDL.Func([IDL.Text], [Campaign], ['query']),
  'getCampaignStats' : IDL.Func([], [IDL.Vec(CampaignStats)], ['query']),
  'getClicksLog' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(ClickEvent)],
      ['query'],
    ),
  'getConversionsLog' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(ConversionEvent)],
      ['query'],
    ),
  'getDomain' : IDL.Func([IDL.Text], [Domain], ['query']),
  'getErrorLog' : IDL.Func([], [IDL.Vec(ErrorLog)], ['query']),
  'getFlow' : IDL.Func([IDL.Text], [Flow], ['query']),
  'getMyProfile' : IDL.Func(
      [IDL.Text],
      [IDL.Record({ 'displayName' : IDL.Text, 'email' : IDL.Text })],
      ['query'],
    ),
  'getOffer' : IDL.Func([IDL.Text], [Offer], ['query']),
  'getStream' : IDL.Func([IDL.Text], [Stream], ['query']),
  'getStreamsByCampaign' : IDL.Func([IDL.Text], [IDL.Vec(Stream)], ['query']),
  'getTrafficSource' : IDL.Func([IDL.Text], [TrafficSource], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initialize' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'logError' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'loginUser' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'logoutUser' : IDL.Func([IDL.Text], [], []),
  'processClick' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [ProcessClickResult],
      [],
    ),
  'processPostback' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64, ConversionStatus],
      [ConversionEvent],
      [],
    ),
  'recordClick' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [ClickEvent],
      [],
    ),
  'recordConversion' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Nat, ConversionStatus],
      [ConversionEvent],
      [],
    ),
  'registerFirstUser' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'registerWithInvite' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setProcessClickRandomValue' : IDL.Func([IDL.Nat], [], []),
  'updateCampaign' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, CampaignStatus, IDL.Text],
      [Campaign],
      [],
    ),
  'updateDomain' : IDL.Func(
      [IDL.Text, IDL.Text, DomainType, DomainStatus],
      [Domain],
      [],
    ),
  'updateFlow' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(RoutingRule)],
      [Flow],
      [],
    ),
  'updateOffer' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, OfferStatus],
      [Offer],
      [],
    ),
  'updateStream' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, StreamState, IDL.Nat],
      [Stream],
      [],
    ),
  'updateTrafficSource' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, CostModel, IDL.Vec(Parameter)],
      [TrafficSource],
      [],
    ),
  'validateSession' : IDL.Func(
      [IDL.Text],
      [IDL.Record({ 'displayName' : IDL.Text, 'email' : IDL.Text })],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CampaignStatus = IDL.Variant({
    'active' : IDL.Null,
    'archived' : IDL.Null,
    'paused' : IDL.Null,
  });
  const Time = IDL.Int;
  const Campaign = IDL.Record({
    'id' : IDL.Text,
    'status' : CampaignStatus,
    'name' : IDL.Text,
    'createdAt' : Time,
    'updatedAt' : Time,
    'trackingDomain' : IDL.Text,
    'campaignKey' : IDL.Text,
    'trafficSourceId' : IDL.Text,
  });
  const DomainType = IDL.Variant({
    'postback' : IDL.Null,
    'admin' : IDL.Null,
    'campaign' : IDL.Null,
  });
  const DomainStatus = IDL.Variant({
    'active' : IDL.Null,
    'inactive' : IDL.Null,
  });
  const Domain = IDL.Record({
    'id' : IDL.Text,
    'status' : DomainStatus,
    'domainType' : DomainType,
    'name' : IDL.Text,
    'createdAt' : Time,
    'updatedAt' : Time,
  });
  const OfferWeight = IDL.Record({ 'weight' : IDL.Nat, 'offerId' : IDL.Text });
  const Condition = IDL.Record({
    'field' : IDL.Text,
    'value' : IDL.Text,
    'operator' : IDL.Text,
  });
  const RoutingRule = IDL.Record({
    'targetOffers' : IDL.Vec(OfferWeight),
    'conditions' : IDL.Vec(Condition),
  });
  const Flow = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Time,
    'campaignId' : IDL.Text,
    'updatedAt' : Time,
    'rules' : IDL.Vec(RoutingRule),
  });
  const OfferStatus = IDL.Variant({ 'active' : IDL.Null, 'paused' : IDL.Null });
  const Offer = IDL.Record({
    'id' : IDL.Text,
    'url' : IDL.Text,
    'status' : OfferStatus,
    'name' : IDL.Text,
    'createdAt' : Time,
    'updatedAt' : Time,
    'currency' : IDL.Text,
    'payout' : IDL.Nat,
  });
  const StreamState = IDL.Variant({ 'active' : IDL.Null, 'paused' : IDL.Null });
  const Stream = IDL.Record({
    'id' : IDL.Text,
    'weight' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : Time,
    'campaignId' : IDL.Text,
    'updatedAt' : Time,
    'state' : StreamState,
    'position' : IDL.Nat,
    'offerId' : IDL.Text,
  });
  const CostModel = IDL.Variant({
    'cpa' : IDL.Null,
    'cpc' : IDL.Null,
    'cpm' : IDL.Null,
  });
  const ParameterType = IDL.Variant({
    'float' : IDL.Null,
    'integer' : IDL.Null,
    'text' : IDL.Null,
    'boolean' : IDL.Null,
    'currency' : IDL.Null,
    'percentage' : IDL.Null,
  });
  const Parameter = IDL.Record({
    'name' : IDL.Text,
    'type' : ParameterType,
    'description' : IDL.Text,
    'required' : IDL.Bool,
  });
  const TrafficSource = IDL.Record({
    'id' : IDL.Text,
    'costModel' : CostModel,
    'name' : IDL.Text,
    'createdAt' : Time,
    'parameters' : IDL.Vec(Parameter),
    'postbackUrl' : IDL.Text,
    'updatedAt' : Time,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const CampaignStats = IDL.Record({
    'epc' : IDL.Nat,
    'roi' : IDL.Nat,
    'clicks' : IDL.Nat,
    'revenue' : IDL.Nat,
    'uniqueClicks' : IDL.Nat,
    'cost' : IDL.Nat,
    'campaignId' : IDL.Text,
    'conversionRate' : IDL.Nat,
    'conversions' : IDL.Nat,
  });
  const ClickEvent = IDL.Record({
    'id' : IDL.Text,
    'os' : IDL.Text,
    'landingPageUrl' : IDL.Text,
    'country' : IDL.Text,
    'city' : IDL.Text,
    'campaignId' : IDL.Text,
    'referrerUrl' : IDL.Text,
    'uniqueClickId' : IDL.Text,
    'timestamp' : Time,
    'deviceType' : IDL.Text,
    'browser' : IDL.Text,
    'ipAddress' : IDL.Text,
  });
  const ConversionStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'declined' : IDL.Null,
  });
  const ConversionEvent = IDL.Record({
    'id' : IDL.Text,
    'status' : ConversionStatus,
    'revenue' : IDL.Nat,
    'campaignId' : IDL.Text,
    'timestamp' : Time,
    'offerId' : IDL.Text,
    'payout' : IDL.Float64,
    'clickId' : IDL.Text,
  });
  const ErrorLog = IDL.Record({
    'id' : IDL.Text,
    'context' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  const ProcessClickResult = IDL.Record({
    'campaignId' : IDL.Text,
    'offerUrl' : IDL.Text,
    'clickId' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCampaign' : IDL.Func(
        [IDL.Text, IDL.Text, CampaignStatus, IDL.Text],
        [Campaign],
        [],
      ),
    'createDomain' : IDL.Func(
        [IDL.Text, DomainType, DomainStatus],
        [Domain],
        [],
      ),
    'createFlow' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(RoutingRule)],
        [Flow],
        [],
      ),
    'createOffer' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, OfferStatus],
        [Offer],
        [],
      ),
    'createStream' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, StreamState, IDL.Nat],
        [Stream],
        [],
      ),
    'createTrafficSource' : IDL.Func(
        [IDL.Text, IDL.Text, CostModel, IDL.Vec(Parameter)],
        [TrafficSource],
        [],
      ),
    'deleteCampaign' : IDL.Func([IDL.Text], [], []),
    'deleteDomain' : IDL.Func([IDL.Text], [], []),
    'deleteFlow' : IDL.Func([IDL.Text], [], []),
    'deleteOffer' : IDL.Func([IDL.Text], [], []),
    'deleteStream' : IDL.Func([IDL.Text], [], []),
    'deleteTrafficSource' : IDL.Func([IDL.Text], [], []),
    'generateInviteToken' : IDL.Func([IDL.Text], [IDL.Text], []),
    'getAllCampaigns' : IDL.Func([], [IDL.Vec(Campaign)], ['query']),
    'getAllDomains' : IDL.Func([], [IDL.Vec(Domain)], ['query']),
    'getAllDomainsByType' : IDL.Func(
        [DomainType],
        [IDL.Vec(Domain)],
        ['query'],
      ),
    'getAllFlows' : IDL.Func([], [IDL.Vec(Flow)], ['query']),
    'getAllOffers' : IDL.Func([], [IDL.Vec(Offer)], ['query']),
    'getAllStreams' : IDL.Func([], [IDL.Vec(Stream)], ['query']),
    'getAllTrafficSources' : IDL.Func([], [IDL.Vec(TrafficSource)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCampaign' : IDL.Func([IDL.Text], [Campaign], ['query']),
    'getCampaignByKey' : IDL.Func([IDL.Text], [Campaign], ['query']),
    'getCampaignStats' : IDL.Func([], [IDL.Vec(CampaignStats)], ['query']),
    'getClicksLog' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(ClickEvent)],
        ['query'],
      ),
    'getConversionsLog' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(ConversionEvent)],
        ['query'],
      ),
    'getDomain' : IDL.Func([IDL.Text], [Domain], ['query']),
    'getErrorLog' : IDL.Func([], [IDL.Vec(ErrorLog)], ['query']),
    'getFlow' : IDL.Func([IDL.Text], [Flow], ['query']),
    'getMyProfile' : IDL.Func(
        [IDL.Text],
        [IDL.Record({ 'displayName' : IDL.Text, 'email' : IDL.Text })],
        ['query'],
      ),
    'getOffer' : IDL.Func([IDL.Text], [Offer], ['query']),
    'getStream' : IDL.Func([IDL.Text], [Stream], ['query']),
    'getStreamsByCampaign' : IDL.Func([IDL.Text], [IDL.Vec(Stream)], ['query']),
    'getTrafficSource' : IDL.Func([IDL.Text], [TrafficSource], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initialize' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'logError' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'loginUser' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'logoutUser' : IDL.Func([IDL.Text], [], []),
    'processClick' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [ProcessClickResult],
        [],
      ),
    'processPostback' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64, ConversionStatus],
        [ConversionEvent],
        [],
      ),
    'recordClick' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [ClickEvent],
        [],
      ),
    'recordConversion' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Nat, ConversionStatus],
        [ConversionEvent],
        [],
      ),
    'registerFirstUser' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'registerWithInvite' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setProcessClickRandomValue' : IDL.Func([IDL.Nat], [], []),
    'updateCampaign' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, CampaignStatus, IDL.Text],
        [Campaign],
        [],
      ),
    'updateDomain' : IDL.Func(
        [IDL.Text, IDL.Text, DomainType, DomainStatus],
        [Domain],
        [],
      ),
    'updateFlow' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(RoutingRule)],
        [Flow],
        [],
      ),
    'updateOffer' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, OfferStatus],
        [Offer],
        [],
      ),
    'updateStream' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, StreamState, IDL.Nat],
        [Stream],
        [],
      ),
    'updateTrafficSource' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, CostModel, IDL.Vec(Parameter)],
        [TrafficSource],
        [],
      ),
    'validateSession' : IDL.Func(
        [IDL.Text],
        [IDL.Record({ 'displayName' : IDL.Text, 'email' : IDL.Text })],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };