/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TrafficSource {
    id: string;
    costModel: CostModel;
    name: string;
    createdAt: Time;
    parameters: Array<Parameter>;
    postbackUrl: string;
    updatedAt: Time;
}
export type Time = bigint;
export interface Condition {
    field: string;
    value: string;
    operator: string;
}
export interface Flow {
    id: string;
    name: string;
    createdAt: Time;
    campaignId: string;
    updatedAt: Time;
    rules: Array<RoutingRule>;
}
export interface Domain {
    id: string;
    status: DomainStatus;
    domainType: DomainType;
    name: string;
    createdAt: Time;
    updatedAt: Time;
}
export interface Parameter {
    name: string;
    type: ParameterType;
    description: string;
    required: boolean;
}
export interface OfferWeight {
    weight: bigint;
    offerId: string;
}
export interface Offer {
    id: string;
    url: string;
    status: OfferStatus;
    name: string;
    createdAt: Time;
    updatedAt: Time;
    currency: string;
    payout: bigint;
}
export interface ConversionEvent {
    id: string;
    status: ConversionStatus;
    revenue: bigint;
    campaignId: string;
    timestamp: Time;
    offerId: string;
    payout: number;
    clickId: string;
}
export interface RoutingRule {
    targetOffers: Array<OfferWeight>;
    conditions: Array<Condition>;
}
export interface CampaignStats {
    epc: bigint;
    roi: bigint;
    clicks: bigint;
    revenue: bigint;
    uniqueClicks: bigint;
    cost: bigint;
    campaignId: string;
    conversionRate: bigint;
    conversions: bigint;
}
export interface Campaign {
    id: string;
    status: CampaignStatus;
    name: string;
    createdAt: Time;
    updatedAt: Time;
    offerIds: Array<OfferWeight>;
    trackingDomain: string;
    trafficSourceId: string;
}
export interface UserProfile {
    name: string;
}
export interface ClickEvent {
    id: string;
    os: string;
    landingPageUrl: string;
    country: string;
    city: string;
    campaignId: string;
    referrerUrl: string;
    uniqueClickId: string;
    timestamp: Time;
    deviceType: string;
    browser: string;
    ipAddress: string;
}
export enum CampaignStatus {
    active = "active",
    archived = "archived",
    paused = "paused"
}
export enum ConversionStatus {
    pending = "pending",
    approved = "approved",
    declined = "declined"
}
export enum CostModel {
    cpa = "cpa",
    cpc = "cpc",
    cpm = "cpm"
}
export enum DomainStatus {
    active = "active",
    inactive = "inactive"
}
export enum DomainType {
    postback = "postback",
    admin = "admin",
    campaign = "campaign"
}
export enum OfferStatus {
    active = "active",
    paused = "paused"
}
export enum ParameterType {
    float_ = "float",
    integer = "integer",
    text = "text",
    boolean_ = "boolean",
    currency = "currency",
    percentage = "percentage"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createCampaign(name: string, trafficSourceId: string, offerIds: Array<OfferWeight>, status: CampaignStatus, trackingDomain: string): Promise<Campaign>;
    createDomain(name: string, domainType: DomainType, status: DomainStatus): Promise<Domain>;
    createFlow(name: string, campaignId: string, rules: Array<RoutingRule>): Promise<Flow>;
    createOffer(name: string, url: string, payout: bigint, currency: string, status: OfferStatus): Promise<Offer>;
    createTrafficSource(name: string, postbackUrl: string, costModel: CostModel, parameters: Array<Parameter>): Promise<TrafficSource>;
    deleteCampaign(id: string): Promise<void>;
    deleteDomain(id: string): Promise<void>;
    deleteFlow(id: string): Promise<void>;
    deleteOffer(id: string): Promise<void>;
    deleteTrafficSource(id: string): Promise<void>;
    getAllCampaigns(): Promise<Array<Campaign>>;
    getAllDomains(): Promise<Array<Domain>>;
    getAllDomainsByType(domainType: DomainType): Promise<Array<Domain>>;
    getAllFlows(): Promise<Array<Flow>>;
    getAllOffers(): Promise<Array<Offer>>;
    getAllTrafficSources(): Promise<Array<TrafficSource>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCampaign(id: string): Promise<Campaign>;
    getCampaignStats(): Promise<Array<CampaignStats>>;
    getClicksLog(page: bigint, pageSize: bigint): Promise<Array<ClickEvent>>;
    getConversionsLog(page: bigint, pageSize: bigint): Promise<Array<ConversionEvent>>;
    getDomain(id: string): Promise<Domain>;
    getFlow(id: string): Promise<Flow>;
    getOffer(id: string): Promise<Offer>;
    getTrafficSource(id: string): Promise<TrafficSource>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    initialize(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    recordClick(campaignId: string, ipAddress: string, country: string, city: string, os: string, browser: string, deviceType: string, referrerUrl: string, landingPageUrl: string): Promise<ClickEvent>;
    recordConversion(clickId: string, campaignId: string, offerId: string, payout: number, revenue: bigint, status: ConversionStatus): Promise<ConversionEvent>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateCampaign(id: string, name: string, trafficSourceId: string, offerIds: Array<OfferWeight>, status: CampaignStatus, trackingDomain: string): Promise<Campaign>;
    updateDomain(id: string, name: string, domainType: DomainType, status: DomainStatus): Promise<Domain>;
    updateFlow(id: string, name: string, campaignId: string, rules: Array<RoutingRule>): Promise<Flow>;
    updateOffer(id: string, name: string, url: string, payout: bigint, currency: string, status: OfferStatus): Promise<Offer>;
    updateTrafficSource(id: string, name: string, postbackUrl: string, costModel: CostModel, parameters: Array<Parameter>): Promise<TrafficSource>;
}
import type { Campaign as _Campaign, CampaignStatus as _CampaignStatus, ConversionEvent as _ConversionEvent, ConversionStatus as _ConversionStatus, CostModel as _CostModel, Domain as _Domain, DomainStatus as _DomainStatus, DomainType as _DomainType, Offer as _Offer, OfferStatus as _OfferStatus, OfferWeight as _OfferWeight, Parameter as _Parameter, ParameterType as _ParameterType, Time as _Time, TrafficSource as _TrafficSource, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createCampaign(arg0: string, arg1: string, arg2: Array<OfferWeight>, arg3: CampaignStatus, arg4: string): Promise<Campaign> {
        if (this.processError) {
            try {
                const result = await this.actor.createCampaign(arg0, arg1, arg2, to_candid_CampaignStatus_n3(this._uploadFile, this._downloadFile, arg3), arg4);
                return from_candid_Campaign_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCampaign(arg0, arg1, arg2, to_candid_CampaignStatus_n3(this._uploadFile, this._downloadFile, arg3), arg4);
            return from_candid_Campaign_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async createDomain(arg0: string, arg1: DomainType, arg2: DomainStatus): Promise<Domain> {
        if (this.processError) {
            try {
                const result = await this.actor.createDomain(arg0, to_candid_DomainType_n9(this._uploadFile, this._downloadFile, arg1), to_candid_DomainStatus_n11(this._uploadFile, this._downloadFile, arg2));
                return from_candid_Domain_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDomain(arg0, to_candid_DomainType_n9(this._uploadFile, this._downloadFile, arg1), to_candid_DomainStatus_n11(this._uploadFile, this._downloadFile, arg2));
            return from_candid_Domain_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async createFlow(arg0: string, arg1: string, arg2: Array<RoutingRule>): Promise<Flow> {
        if (this.processError) {
            try {
                const result = await this.actor.createFlow(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createFlow(arg0, arg1, arg2);
            return result;
        }
    }
    async createOffer(arg0: string, arg1: string, arg2: bigint, arg3: string, arg4: OfferStatus): Promise<Offer> {
        if (this.processError) {
            try {
                const result = await this.actor.createOffer(arg0, arg1, arg2, arg3, to_candid_OfferStatus_n19(this._uploadFile, this._downloadFile, arg4));
                return from_candid_Offer_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOffer(arg0, arg1, arg2, arg3, to_candid_OfferStatus_n19(this._uploadFile, this._downloadFile, arg4));
            return from_candid_Offer_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async createTrafficSource(arg0: string, arg1: string, arg2: CostModel, arg3: Array<Parameter>): Promise<TrafficSource> {
        if (this.processError) {
            try {
                const result = await this.actor.createTrafficSource(arg0, arg1, to_candid_CostModel_n25(this._uploadFile, this._downloadFile, arg2), to_candid_vec_n27(this._uploadFile, this._downloadFile, arg3));
                return from_candid_TrafficSource_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTrafficSource(arg0, arg1, to_candid_CostModel_n25(this._uploadFile, this._downloadFile, arg2), to_candid_vec_n27(this._uploadFile, this._downloadFile, arg3));
            return from_candid_TrafficSource_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteCampaign(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCampaign(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCampaign(arg0);
            return result;
        }
    }
    async deleteDomain(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDomain(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDomain(arg0);
            return result;
        }
    }
    async deleteFlow(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFlow(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFlow(arg0);
            return result;
        }
    }
    async deleteOffer(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteOffer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteOffer(arg0);
            return result;
        }
    }
    async deleteTrafficSource(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTrafficSource(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTrafficSource(arg0);
            return result;
        }
    }
    async getAllCampaigns(): Promise<Array<Campaign>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCampaigns();
                return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCampaigns();
            return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllDomains(): Promise<Array<Domain>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDomains();
                return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDomains();
            return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllDomainsByType(arg0: DomainType): Promise<Array<Domain>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDomainsByType(to_candid_DomainType_n9(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDomainsByType(to_candid_DomainType_n9(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllFlows(): Promise<Array<Flow>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllFlows();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllFlows();
            return result;
        }
    }
    async getAllOffers(): Promise<Array<Offer>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllOffers();
                return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllOffers();
            return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTrafficSources(): Promise<Array<TrafficSource>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTrafficSources();
                return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTrafficSources();
            return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCampaign(arg0: string): Promise<Campaign> {
        if (this.processError) {
            try {
                const result = await this.actor.getCampaign(arg0);
                return from_candid_Campaign_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCampaign(arg0);
            return from_candid_Campaign_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCampaignStats(): Promise<Array<CampaignStats>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCampaignStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCampaignStats();
            return result;
        }
    }
    async getClicksLog(arg0: bigint, arg1: bigint): Promise<Array<ClickEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getClicksLog(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClicksLog(arg0, arg1);
            return result;
        }
    }
    async getConversionsLog(arg0: bigint, arg1: bigint): Promise<Array<ConversionEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getConversionsLog(arg0, arg1);
                return from_candid_vec_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getConversionsLog(arg0, arg1);
            return from_candid_vec_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDomain(arg0: string): Promise<Domain> {
        if (this.processError) {
            try {
                const result = await this.actor.getDomain(arg0);
                return from_candid_Domain_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDomain(arg0);
            return from_candid_Domain_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFlow(arg0: string): Promise<Flow> {
        if (this.processError) {
            try {
                const result = await this.actor.getFlow(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFlow(arg0);
            return result;
        }
    }
    async getOffer(arg0: string): Promise<Offer> {
        if (this.processError) {
            try {
                const result = await this.actor.getOffer(arg0);
                return from_candid_Offer_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOffer(arg0);
            return from_candid_Offer_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTrafficSource(arg0: string): Promise<TrafficSource> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrafficSource(arg0);
                return from_candid_TrafficSource_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrafficSource(arg0);
            return from_candid_TrafficSource_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async initialize(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initialize();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initialize();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async recordClick(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string, arg7: string, arg8: string): Promise<ClickEvent> {
        if (this.processError) {
            try {
                const result = await this.actor.recordClick(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordClick(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
            return result;
        }
    }
    async recordConversion(arg0: string, arg1: string, arg2: string, arg3: number, arg4: bigint, arg5: ConversionStatus): Promise<ConversionEvent> {
        if (this.processError) {
            try {
                const result = await this.actor.recordConversion(arg0, arg1, arg2, arg3, arg4, to_candid_ConversionStatus_n53(this._uploadFile, this._downloadFile, arg5));
                return from_candid_ConversionEvent_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordConversion(arg0, arg1, arg2, arg3, arg4, to_candid_ConversionStatus_n53(this._uploadFile, this._downloadFile, arg5));
            return from_candid_ConversionEvent_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateCampaign(arg0: string, arg1: string, arg2: string, arg3: Array<OfferWeight>, arg4: CampaignStatus, arg5: string): Promise<Campaign> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCampaign(arg0, arg1, arg2, arg3, to_candid_CampaignStatus_n3(this._uploadFile, this._downloadFile, arg4), arg5);
                return from_candid_Campaign_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCampaign(arg0, arg1, arg2, arg3, to_candid_CampaignStatus_n3(this._uploadFile, this._downloadFile, arg4), arg5);
            return from_candid_Campaign_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateDomain(arg0: string, arg1: string, arg2: DomainType, arg3: DomainStatus): Promise<Domain> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDomain(arg0, arg1, to_candid_DomainType_n9(this._uploadFile, this._downloadFile, arg2), to_candid_DomainStatus_n11(this._uploadFile, this._downloadFile, arg3));
                return from_candid_Domain_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDomain(arg0, arg1, to_candid_DomainType_n9(this._uploadFile, this._downloadFile, arg2), to_candid_DomainStatus_n11(this._uploadFile, this._downloadFile, arg3));
            return from_candid_Domain_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateFlow(arg0: string, arg1: string, arg2: string, arg3: Array<RoutingRule>): Promise<Flow> {
        if (this.processError) {
            try {
                const result = await this.actor.updateFlow(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateFlow(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateOffer(arg0: string, arg1: string, arg2: string, arg3: bigint, arg4: string, arg5: OfferStatus): Promise<Offer> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOffer(arg0, arg1, arg2, arg3, arg4, to_candid_OfferStatus_n19(this._uploadFile, this._downloadFile, arg5));
                return from_candid_Offer_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOffer(arg0, arg1, arg2, arg3, arg4, to_candid_OfferStatus_n19(this._uploadFile, this._downloadFile, arg5));
            return from_candid_Offer_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateTrafficSource(arg0: string, arg1: string, arg2: string, arg3: CostModel, arg4: Array<Parameter>): Promise<TrafficSource> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTrafficSource(arg0, arg1, arg2, to_candid_CostModel_n25(this._uploadFile, this._downloadFile, arg3), to_candid_vec_n27(this._uploadFile, this._downloadFile, arg4));
                return from_candid_TrafficSource_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTrafficSource(arg0, arg1, arg2, to_candid_CostModel_n25(this._uploadFile, this._downloadFile, arg3), to_candid_vec_n27(this._uploadFile, this._downloadFile, arg4));
            return from_candid_TrafficSource_n32(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_CampaignStatus_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CampaignStatus): CampaignStatus {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_Campaign_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Campaign): Campaign {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_ConversionEvent_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ConversionEvent): ConversionEvent {
    return from_candid_record_n50(_uploadFile, _downloadFile, value);
}
function from_candid_ConversionStatus_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ConversionStatus): ConversionStatus {
    return from_candid_variant_n52(_uploadFile, _downloadFile, value);
}
function from_candid_CostModel_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CostModel): CostModel {
    return from_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function from_candid_DomainStatus_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DomainStatus): DomainStatus {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_DomainType_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DomainType): DomainType {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_Domain_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Domain): Domain {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_OfferStatus_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OfferStatus): OfferStatus {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_Offer_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Offer): Offer {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_ParameterType_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ParameterType): ParameterType {
    return from_candid_variant_n40(_uploadFile, _downloadFile, value);
}
function from_candid_Parameter_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Parameter): Parameter {
    return from_candid_record_n38(_uploadFile, _downloadFile, value);
}
function from_candid_TrafficSource_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TrafficSource): TrafficSource {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n47(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _DomainStatus;
    domainType: _DomainType;
    name: string;
    createdAt: _Time;
    updatedAt: _Time;
}): {
    id: string;
    status: DomainStatus;
    domainType: DomainType;
    name: string;
    createdAt: Time;
    updatedAt: Time;
} {
    return {
        id: value.id,
        status: from_candid_DomainStatus_n15(_uploadFile, _downloadFile, value.status),
        domainType: from_candid_DomainType_n17(_uploadFile, _downloadFile, value.domainType),
        name: value.name,
        createdAt: value.createdAt,
        updatedAt: value.updatedAt
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    url: string;
    status: _OfferStatus;
    name: string;
    createdAt: _Time;
    updatedAt: _Time;
    currency: string;
    payout: bigint;
}): {
    id: string;
    url: string;
    status: OfferStatus;
    name: string;
    createdAt: Time;
    updatedAt: Time;
    currency: string;
    payout: bigint;
} {
    return {
        id: value.id,
        url: value.url,
        status: from_candid_OfferStatus_n23(_uploadFile, _downloadFile, value.status),
        name: value.name,
        createdAt: value.createdAt,
        updatedAt: value.updatedAt,
        currency: value.currency,
        payout: value.payout
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    costModel: _CostModel;
    name: string;
    createdAt: _Time;
    parameters: Array<_Parameter>;
    postbackUrl: string;
    updatedAt: _Time;
}): {
    id: string;
    costModel: CostModel;
    name: string;
    createdAt: Time;
    parameters: Array<Parameter>;
    postbackUrl: string;
    updatedAt: Time;
} {
    return {
        id: value.id,
        costModel: from_candid_CostModel_n34(_uploadFile, _downloadFile, value.costModel),
        name: value.name,
        createdAt: value.createdAt,
        parameters: from_candid_vec_n36(_uploadFile, _downloadFile, value.parameters),
        postbackUrl: value.postbackUrl,
        updatedAt: value.updatedAt
    };
}
function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    type: _ParameterType;
    description: string;
    required: boolean;
}): {
    name: string;
    type: ParameterType;
    description: string;
    required: boolean;
} {
    return {
        name: value.name,
        type: from_candid_ParameterType_n39(_uploadFile, _downloadFile, value.type),
        description: value.description,
        required: value.required
    };
}
function from_candid_record_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _ConversionStatus;
    revenue: bigint;
    campaignId: string;
    timestamp: _Time;
    offerId: string;
    payout: number;
    clickId: string;
}): {
    id: string;
    status: ConversionStatus;
    revenue: bigint;
    campaignId: string;
    timestamp: Time;
    offerId: string;
    payout: number;
    clickId: string;
} {
    return {
        id: value.id,
        status: from_candid_ConversionStatus_n51(_uploadFile, _downloadFile, value.status),
        revenue: value.revenue,
        campaignId: value.campaignId,
        timestamp: value.timestamp,
        offerId: value.offerId,
        payout: value.payout,
        clickId: value.clickId
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _CampaignStatus;
    name: string;
    createdAt: _Time;
    updatedAt: _Time;
    offerIds: Array<_OfferWeight>;
    trackingDomain: string;
    trafficSourceId: string;
}): {
    id: string;
    status: CampaignStatus;
    name: string;
    createdAt: Time;
    updatedAt: Time;
    offerIds: Array<OfferWeight>;
    trackingDomain: string;
    trafficSourceId: string;
} {
    return {
        id: value.id,
        status: from_candid_CampaignStatus_n7(_uploadFile, _downloadFile, value.status),
        name: value.name,
        createdAt: value.createdAt,
        updatedAt: value.updatedAt,
        offerIds: value.offerIds,
        trackingDomain: value.trackingDomain,
        trafficSourceId: value.trafficSourceId
    };
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    inactive: null;
}): DomainStatus {
    return "active" in value ? DomainStatus.active : "inactive" in value ? DomainStatus.inactive : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    postback: null;
} | {
    admin: null;
} | {
    campaign: null;
}): DomainType {
    return "postback" in value ? DomainType.postback : "admin" in value ? DomainType.admin : "campaign" in value ? DomainType.campaign : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    paused: null;
}): OfferStatus {
    return "active" in value ? OfferStatus.active : "paused" in value ? OfferStatus.paused : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cpa: null;
} | {
    cpc: null;
} | {
    cpm: null;
}): CostModel {
    return "cpa" in value ? CostModel.cpa : "cpc" in value ? CostModel.cpc : "cpm" in value ? CostModel.cpm : value;
}
function from_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    float: null;
} | {
    integer: null;
} | {
    text: null;
} | {
    boolean: null;
} | {
    currency: null;
} | {
    percentage: null;
}): ParameterType {
    return "float" in value ? ParameterType.float : "integer" in value ? ParameterType.integer : "text" in value ? ParameterType.text : "boolean" in value ? ParameterType.boolean : "currency" in value ? ParameterType.currency : "percentage" in value ? ParameterType.percentage : value;
}
function from_candid_variant_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    declined: null;
}): ConversionStatus {
    return "pending" in value ? ConversionStatus.pending : "approved" in value ? ConversionStatus.approved : "declined" in value ? ConversionStatus.declined : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    archived: null;
} | {
    paused: null;
}): CampaignStatus {
    return "active" in value ? CampaignStatus.active : "archived" in value ? CampaignStatus.archived : "paused" in value ? CampaignStatus.paused : value;
}
function from_candid_vec_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Parameter>): Array<Parameter> {
    return value.map((x)=>from_candid_Parameter_n37(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Campaign>): Array<Campaign> {
    return value.map((x)=>from_candid_Campaign_n5(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Domain>): Array<Domain> {
    return value.map((x)=>from_candid_Domain_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Offer>): Array<Offer> {
    return value.map((x)=>from_candid_Offer_n21(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TrafficSource>): Array<TrafficSource> {
    return value.map((x)=>from_candid_TrafficSource_n32(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ConversionEvent>): Array<ConversionEvent> {
    return value.map((x)=>from_candid_ConversionEvent_n49(_uploadFile, _downloadFile, x));
}
function to_candid_CampaignStatus_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CampaignStatus): _CampaignStatus {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_ConversionStatus_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ConversionStatus): _ConversionStatus {
    return to_candid_variant_n54(_uploadFile, _downloadFile, value);
}
function to_candid_CostModel_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CostModel): _CostModel {
    return to_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function to_candid_DomainStatus_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DomainStatus): _DomainStatus {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_DomainType_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DomainType): _DomainType {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_OfferStatus_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OfferStatus): _OfferStatus {
    return to_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function to_candid_ParameterType_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ParameterType): _ParameterType {
    return to_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function to_candid_Parameter_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Parameter): _Parameter {
    return to_candid_record_n29(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    type: ParameterType;
    description: string;
    required: boolean;
}): {
    name: string;
    type: _ParameterType;
    description: string;
    required: boolean;
} {
    return {
        name: value.name,
        type: to_candid_ParameterType_n30(_uploadFile, _downloadFile, value.type),
        description: value.description,
        required: value.required
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DomainType): {
    postback: null;
} | {
    admin: null;
} | {
    campaign: null;
} {
    return value == DomainType.postback ? {
        postback: null
    } : value == DomainType.admin ? {
        admin: null
    } : value == DomainType.campaign ? {
        campaign: null
    } : value;
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DomainStatus): {
    active: null;
} | {
    inactive: null;
} {
    return value == DomainStatus.active ? {
        active: null
    } : value == DomainStatus.inactive ? {
        inactive: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OfferStatus): {
    active: null;
} | {
    paused: null;
} {
    return value == OfferStatus.active ? {
        active: null
    } : value == OfferStatus.paused ? {
        paused: null
    } : value;
}
function to_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CostModel): {
    cpa: null;
} | {
    cpc: null;
} | {
    cpm: null;
} {
    return value == CostModel.cpa ? {
        cpa: null
    } : value == CostModel.cpc ? {
        cpc: null
    } : value == CostModel.cpm ? {
        cpm: null
    } : value;
}
function to_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ParameterType): {
    float: null;
} | {
    integer: null;
} | {
    text: null;
} | {
    boolean: null;
} | {
    currency: null;
} | {
    percentage: null;
} {
    return value == ParameterType.float ? {
        float_: null
    } : value == ParameterType.integer ? {
        integer: null
    } : value == ParameterType.text ? {
        text: null
    } : value == ParameterType.boolean ? {
        boolean_: null
    } : value == ParameterType.currency ? {
        currency: null
    } : value == ParameterType.percentage ? {
        percentage: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CampaignStatus): {
    active: null;
} | {
    archived: null;
} | {
    paused: null;
} {
    return value == CampaignStatus.active ? {
        active: null
    } : value == CampaignStatus.archived ? {
        archived: null
    } : value == CampaignStatus.paused ? {
        paused: null
    } : value;
}
function to_candid_variant_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ConversionStatus): {
    pending: null;
} | {
    approved: null;
} | {
    declined: null;
} {
    return value == ConversionStatus.pending ? {
        pending: null
    } : value == ConversionStatus.approved ? {
        approved: null
    } : value == ConversionStatus.declined ? {
        declined: null
    } : value;
}
function to_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Parameter>): Array<_Parameter> {
    return value.map((x)=>to_candid_Parameter_n28(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
